### ISSUE TITLE
File could not be found error

### ISSUE THREAD

**Issue by t3h2mas** [GerbenJavado/LinkFinder#25]
When you don't prefix the input URL with http/https the script fails with a non obvious error:
```
Usage: python linkfinder.py [Options] use -h for help
Error: file could not         be found.
```

This might trip new users up. I suggest either 

1. checking the url and suggesting they add http or https
2. adding a comment to the 'file could not be found' error message such as
```
Error: file could not         be found.
(did you remember to specify either http or https?)
```

**Comment by EdOverflow** [comment]
Updating the following snippet could solve this issue:
https://github.com/GerbenJavado/LinkFinder/blob/a5fa9bfeee02d4a4672e5eb1c1442dbfba197880/linkfinder.py#L93-L96

**Comment by GerbenJavado** [comment]
Thank you for the suggestion @t3h2mas and sorry for the late response (missed this one). Issue has been addressed in commit https://github.com/GerbenJavado/LinkFinder/commit/2402ed6f4267947b8a182458e08abda8e6e05c08. Writing an automatic pre-fixer would have required a lot more work, since we also want to scan local files. Thus, I went with the lazy option.

**Comment by t3h2mas** [comment]
Appreciate it :)
